### ISSUE TITLE
Plotting fit takes too much time 

### ISSUE THREAD

**Issue by crusher083** [erdogant/distfit#11]
A result of distribution fitting takes ~ 3 minutes to plot. Using this becomes unfeasible for multiple distributions fitting.

**Comment by erdogant** [comment]
In order to help, you need to give a code example what you do and where it takes to much time.

**Comment by crusher083** [comment]
I rechecked if that was a problem with my machine, but it doesn't look so.
```
import numpy
from distfit import distfit
from datetime import datetime 

dist = distfit(todf=True, method='discrete')
dist.fit_transform(np.random.binomial(1, 0.48, 250))

start_time = datetime.now() 
dist.plot()
# Next jupyter cell
print('Time elapsed (hh:mm:ss.ms) {}'.format(datetime.now() - start_time))
Time elapsed (hh:mm:ss.ms) 0:02:50.604459
```

Python implementation: CPython
Python version       : 3.9.2
IPython version      : 7.22.0
numpy      : 1.19.2

Compiler    : MSC v.1916 64 bit (AMD64)
OS          : Windows
Release     : 10
Machine     : AMD64
Processor   : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
CPU cores   : 8
Architecture: 64bit

**Comment by crusher083** [comment]
Okay, I guess it was problem with my machine after all, restarting kernel reduced this times. Sorry. 
Great library!

**Comment by erdogant** [comment]
Great! Well you can speedup the proces by setting the parameter todf=False. Pandas is really a bottleneck. The results are also stored in a dict for further usage!
