### ISSUE TITLE
I have a confusion about dist.results

### ISSUE THREAD

**Issue by wanglinxiao** [erdogant/distfit#14]
The output of dist.results has four columns, I want to know the difference between column "y_pred" and column "P". What I understand is that column "P" represents pvalue and column "y_pred" represents fdr corrected pvalue, please tell me that my understanding is right or not.

**Comment by erdogant** [comment]
You are right, this was not described very clearly.
I updated the readme and [sphinx pages](https://erdogant.github.io/distfit/pages/html/Examples.html#extract-results).

It is as follows:
```
# y: input values
# y_proba: corrected P-values after multiple test correction (default: fdr_bh).
# y_pred: True in case y_proba<=alpha
# P: raw P-values
# Set "multtest" to None during initialization if you want to work with the raw P-values.

```
