### ISSUE TITLE
Can I use the best distribution as the true distribution of my data?

### ISSUE THREAD

**Issue by yuanfuqiang456** [erdogant/distfit#17]
Here I used distfit to get a distribution that is the closest to my data，but not exactly。When I use the kstest from the scipy library to calculate the p-value to see if I can trust the distribution, the p-value is not ideal.Can I still use distfit to get a distribution to describe my data ?

**Comment by yuanfuqiang456** [comment]
GOF is used to measure the effect of fitting. Scores for most predicted distributions (obtained via dist.summary) are relatively small, much less than 1, including the normal distribution fitting cases provided in the documentation. In theory, does it mean that the closer to 1, the better the distribution?
The example is 
from distfit import distfit
import numpy as np
X = np.random.normal(0, 2, [100,10])
y = [-8,-6,0,1,2,3,4,5,6]
dist = distfit(todf=True)
dist.fit_transform(X)
dist.plot()
dist.summary

**Comment by yuanfuqiang456** [comment]
Here I use scipy.stats to randomly generate a set of pareto data, fit it with dist, and the results show that it obeys the beta distribution. Am I doing something wrong here?
import scipy.stats as st
pareto_smp = st.pareto.rvs(loc=-1.71832, scale=1.71832, b=0.75269, size=18168)
dist = distfit(todf=True)
dist.fit_transform(pareto_smp)
dist.plot()
The result is that :
[distfit] >fit..
[distfit] >transform..
[distfit] >[norm      ] [0.00 sec] [RSS: 0.0000000] [loc=205.261 scale=9107.128]
[distfit] >[expon     ] [0.0 sec] [RSS: 0.0000000] [loc=0.000 scale=205.261]
[distfit] >[pareto    ] [0.41 sec] [RSS: 0.0000000] [loc=-2.811 scale=2.812]
[distfit] >[dweibull  ] [0.28 sec] [RSS: 0.0000000] [loc=0.737 scale=3978.635]
[distfit] >[t         ] [0.05 sec] [RSS: 0.0000000] [loc=1.254 scale=1.267]
[distfit] >[genextreme] [0.30 sec] [RSS: 0.0000000] [loc=1.249 scale=2.090]
[distfit] >[gamma     ] [0.18 sec] [RSS: 0.0000000] [loc=0.000 scale=4.241]
[distfit] >[lognorm   ] [0.24 sec] [RSS: 0.0000000] [loc=-0.002 scale=2.843]
[distfit] >[beta      ] [0.37 sec] [RSS: 0.0000000] [loc=0.000 scale=9339422.210]
[distfit] >[uniform   ] [0.0 sec] [RSS: 0.0000000] [loc=0.000 scale=1048788.945]
[distfit] >[loggamma  ] [0.27 sec] [RSS: 0.0000000] [loc=-245551.102 scale=43097.376]
[distfit] >Compute confidence interval [parametric]
[distfit] >plot..

**Comment by erdogant** [comment]
I created a small benchmark to see how well the Pareto distribution is fitted. The point is that under some conditions (loc/scale), certain distributions, like gamma and beta distribution become alike. I am not sure whether Pareto has close families under certain parameters.

The underneath code will store the ranking of the fit for the pareto distribution under various conditions. I will run over 2 different statistics to compute the fit (RSS and wasserstein), I increase the bin sizes (default is 50), I change the sample sizes, and change the pareto b value.

```
from distfit import distfit
import scipy.stats as st
import pandas as pd

ranking = []
b_pareto = [0.75, 1, 2, 3, 4, 5]
sample_sizes = [100, 1000, 10000]
bins = [50, 100, 200]
stats = ['RSS', 'wasserstein']

for stat in stats:
    for bs in bins:
        for b in b_pareto:
            for s in sample_sizes:
                X = st.pareto.rvs(b, size=s)
                dist = distfit(todf=True, stats=stat, bins=bs)
                dist.fit_transform(X)
                r = np.where(dist.summary['distr']=='pareto')[0][0]
                ranking.append([r, b, s, bs, stat])

df = pd.DataFrame(ranking, columns=['rank','b','sample size', 'bins', 'stats'])

```
Let's now check out how the ranking is in the 108 fits we created.
The Pareto distribution is ranked in 90% of all cases in the top 3 and 81% <=2. This is pretty good I would say.
```
np.sum(df['rank']<=3) / df.shape[0]
0.907407407407

```

If we investigate which fits did not work out so well, aka those that ranked out of the top 3, then we see that the `b` value was <= 1 a lot of times and maybe the RSS stats results in a less better fit compared to wasserstein. 
```
df.loc[df['rank']>=3, :]

    rank     b  sample size  bins        stats
0      4  0.75          100    50          RSS
1      7  0.75         1000    50          RSS
2      5  0.75        10000    50          RSS
4      3  1.00         1000    50          RSS
5      3  1.00        10000    50          RSS
10     3  3.00         1000    50          RSS
19     9  0.75         1000   100          RSS
20     6  0.75        10000   100          RSS
22     3  1.00         1000   100          RSS
23     6  1.00        10000   100          RSS
37     3  0.75         1000   200          RSS
38     5  0.75        10000   200          RSS
40     4  1.00         1000   200          RSS
41     3  1.00        10000   200          RSS
45     3  3.00          100   200          RSS
56     4  0.75        10000    50  wasserstein
69     3  5.00          100    50  wasserstein
73     4  0.75         1000   100  wasserstein
91     3  0.75         1000   200  wasserstein
94     3  1.00         1000   200  wasserstein

```

 So overall, It seems that ``distfit`` does do a good job but not maybe not so much under the conditions with b<=1.
