### ISSUE TITLE
Save best parameters

### ISSUE THREAD

**Issue by hummm310** [erdogant/distfit#22]
Hello,
your package really useful, thanks a lot!

I have a question:
If I want to print the best parameters, what's the syntax?
For example, I want to print the best n and p for binomial distribution for the following work.

thanks a lot

**Comment by erdogant** [comment]
All the model parameters are stored in `dist.model`
Does the [documentation page](https://erdogant.github.io/distfit/pages/html/Discrete.html#binomial-distribution) maybe help to solve your issue?

**Comment by hummm310** [comment]
> All the model parameters are stored in Does the [documentation page](https://erdogant.github.io/distfit/pages/html/Discrete.html#binomial-distribution) maybe help to solve your issue?`dist.model`

yes, thanks a lot!
