### ISSUE TITLE
Plots are not generated

### ISSUE THREAD

**Issue by danishTUE** [erdogant/distfit#24]
Hi,

Both dist.plot() and  dist.plot_summary() do not generate plots for me. I am using the bare version of Python (i.e no Conda etc.)

Am I missing somethings?

Regards,

Danish

**Comment by danishTUE** [comment]
Figured it now. I needed to write plt.show() at the end of the code. Nevermind, thanks!

**Comment by erdogant** [comment]
Great! I was trying to see whether I could reproduce the error. Glad to see that it is fixed 👍🏻
