### ISSUE TITLE
A code snippet for `plotting` the best fit and the original data

### ISSUE THREAD

**Issue by luo-lorry** [erdogant/distfit#25]
Thank you for this useful and practical package! Would it be possible to include the feature to plot the best-fit model over the original data? I hope my tentative solution might help other users. 

The best-fit model and the actual data can be plotted using the code below.
```
from distfit import distfit

fig, ax = plt.subplots()
dist = distfit(alpha=0.05, smooth=10)
dist.fit_transform(data)
best_distr = dist.model
exec(f"from scipy.stats import {best_distr['name']}")
ax.hist(data, density=True, label="data")
data_range = np.linspace(data.min(), data.max())
ax.plot(data_range, getattr(scipy.stats, best_distr['name']).pdf(data_range, *best_distr['params']), color='r', lw=4, label=f"{best_distr['name']} ({best_distr['stats']}={best_distr['score']:.3f})")
ax.legend()
```

![download](https://user-images.githubusercontent.com/113964816/215960034-52f73485-b7d5-448a-8dd2-b57f725668ee.png)

**Comment by erdogant** [comment]
Thank you for the suggestion!
I recently created an update in the plots. Creating Pareto plots is now possible!
Checkout the [documentation pages](https://erdogant.github.io/distfit/pages/html/Plots.html) for details.

Your figure can be created by customizing the different elements on the plot.

```
fig, ax = dfit.plot(chart='PDF',
                pdf_properties={'color': 'r', 'linewidth': 3},
                cii_properties=None,
                emp_properties={'linewidth': 1},
                bar_properties={'color': '#1e3f5a'})
```

Let me know if something is not clear.

Update to the latest version with:
`pip install -U distfit
`


![image](https://user-images.githubusercontent.com/31008129/215992417-ae3d230b-6537-4f8b-b932-fc0cdc37ff03.png)

**Comment by luo-lorry** [comment]
I appreciate your prompt reply, and I'll give it a shot. A follow-up question, why do the fitted curves (other than the best fit `beta`) look more like CDF rather than PDF in this plot?

**Comment by erdogant** [comment]
True. Because I accidentally copy-paste the wrong one.

![image](https://user-images.githubusercontent.com/31008129/216083794-f39957c7-85b4-49f8-a63c-81e1eee24af8.png)
