### ISSUE TITLE
plot_summary throws error

### ISSUE THREAD

**Issue by rameshiyerv** [erdogant/distfit#28]
This is a great library, find it quite useful.

The following is a potential bug that needs to be addressed.
distfit.plot_summary() throws the error - set_tick() got an unexpected keyword argument 'rotation'

----stack trace---
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-436-c4c81cc9b0ab> in <module>
----> 1 empDist.plot_summary()

c:\users\iyerram\appdata\local\programs\python\python37\lib\site-packages\distfit\distfit.py in plot_summary(self, n_top, figsize, ylim, fig, ax, grid, color_y1, color_y2, verbose)
   1100 
   1101             # You can specify a rotation for the tick labels in degrees or with keywords.
-> 1102             ax.set_xticks(xcoord, df['name'].values, rotation=45)
   1103 
   1104             # Pad margins so that markers don't get clipped by the axes

c:\users\iyerram\appdata\local\programs\python\python37\lib\site-packages\matplotlib\axes\_base.py in wrapper(self, *args, **kwargs)
     61 
     62         def wrapper(self, *args, **kwargs):
---> 63             return get_method(self)(*args, **kwargs)
     64 
     65         wrapper.__module__ = owner.__module__

c:\users\iyerram\appdata\local\programs\python\python37\lib\site-packages\matplotlib\cbook\deprecation.py in wrapper(*args, **kwargs)
    449                 "parameter will become keyword-only %(removal)s.",
    450                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 451         return func(*args, **kwargs)
    452 
    453     return wrapper

TypeError: set_ticks() got an unexpected keyword argument 'rotation'

image:
![image](https://user-images.githubusercontent.com/64004013/219696807-cc80c403-3e7e-49cc-88bd-b3c907fe1527.png)

**Comment by erdogant** [comment]
This error occurs when matplotlib version is not up-to-date.
`pip install -U matplotlib`

I released a new version that checks the version of matplotlib and gives a warning to update if required.

**Comment by erdogant** [comment]
Should be fixed now. Let me know if it is not.
