### ISSUE TITLE
extend __init__.py descriptions

### ISSUE THREAD

**Issue by carloocchiena** [erdogant/distfit#29]
I am not sure if this qualifies as an issue, but the distfit help on IPython (such as "distfit??") returns a minimum set of information.
Would be nice (and helpful) to include p.e. a list of all the methods included and some more extended documentation.
I may be glad to help p.e. if the raw doc is available somewhere and need to be formatted and included in the file. 
thanks!

**Comment by erdogant** [comment]
Over[here](https://erdogant.github.io/distfit/) are the documentation pages. Is that what you are looking for?

**Comment by carloocchiena** [comment]
yep but usually a larger chunk of them are included in the __init__ to be displayed in JNotebooks, Colab and such
while the actual "distfit??"returns a very small doc.

**Comment by erdogant** [comment]
Thanks for this feedback! I moved the docstrings and created a new version. 
Update with: `pip install -U distfit`
