### ISSUE TITLE
Two questions about distfit

### ISSUE THREAD

**Issue by lesshaste** [erdogant/distfit#3]
This project looks really great, thank you. I have two questions:

 - How do you set loc = 0 if you know that is the right value for it? I am trying to fit to a symmetric distribution.
 - When I try distfit with distr='full' it gets stuck at levy_l.  Is this expected?

**Comment by erdogant** [comment]
Dear lesshaste, Thank you for your feedback! 
You are right about levy_l (and also stable), these are very slow so I removed them from the full list.
The loc parameter is automatically determined. There is no input parameter to force this to be a specified value. 
Can you describe why you want to fixate this parameter? 

try to pip install the new version with:
    `pip install -U distfit`

**Comment by lesshaste** [comment]
Thank you for the reply.  In my case I know the distribution is symmetric with mean (and median) 0.  So it makes sense to use that information I was thinking.

**Comment by erdogant** [comment]
I you have sufficient data, your mean value will be towards zero. Maybe not exactly 0 but very close to it. If your data is symmetric, it will try to fit a distribution that shows the best fit. The fun part is that you do not have to worry about these parameters but are estimated for you. 

For example a normal distribution with 10000 data points with mean ~0

```
X = np.random.normal(0, 2, 10000)
y = [-8,-6,0,1,2,3,4,5,6]
dist = distfit()
model = dist.fit_transform(X)
dist.plot()

```

This gives the following output:

[distfit] >[norm      ] [RSS: 0.0009400] [loc=0.017 scale=1.993] 
[distfit] >[expon     ] [RSS: 0.3300147] [loc=-8.140 scale=8.157] 
[distfit] >[pareto    ] [RSS: 0.3251750] [loc=-406937692.614 scale=406937684.474] 
[distfit] >[dweibull  ] [RSS: 0.0070768] [loc=0.011 scale=1.698] 
[distfit] >[t         ] [RSS: 0.0009299] [loc=0.017 scale=1.988] 
[distfit] >[genextreme] [RSS: 0.0028985] [loc=-0.759 scale=1.961] 
[distfit] >[gamma     ] [RSS: 0.0008770] [loc=-85.198 scale=0.047] 
[distfit] >[lognorm   ] [RSS: 0.0009010] [loc=-74.206 scale=74.190] 
[distfit] >[beta      ] [RSS: 0.0008786] [loc=-82.021 scale=25037346.492] 
[distfit] >[uniform   ] [RSS: 0.2463460] [loc=-8.140 scale=16.556] 

In case of a normal distribution the location (loc) keyword specifies the mean. The scale (scale) keyword specifies the standard deviation. But in different distribution these can have different properties. Mostly to shift and/or scale the distribution.

https://docs.scipy.org/doc/scipy/reference/stats.html
