### ISSUE TITLE
Help needed to interpret loc and scale

### ISSUE THREAD

**Issue by jamesee** [erdogant/distfit#31]
Hi

Thank you for the great library. 

I have been using it to fit my data and have the following great result. However, while I can fully understand the a=12.8672 and b=12.86672, I am have difficulty interpreting what loc and scale are. From the document, it seems to be mean and std-dev.

I know the distribution mean is at 25 and std-dev=5.4645.
<img width="548" alt="Screenshot 2023-03-07 at 11 59 16 AM" src="https://user-images.githubusercontent.com/37786118/223317359-58cf1623-cf8f-4805-a510-395a8784464c.png">

Are you able to show me how I should convert the loc and scale to get mean=25 and std-dev=5.4645 ?.

Many thanks in advance.

<img width="665" alt="Sum-plots" src="https://user-images.githubusercontent.com/37786118/223314621-b5d4934d-6570-4188-98dc-cea94f2e6606.png">

**Comment by jamesee** [comment]
Hi,

I found the answer. Thanks anyway.

Thank you for the great library. :)

<img width="933" alt="Screenshot 2023-03-07 at 2 04 32 PM" src="https://user-images.githubusercontent.com/37786118/223334700-2c4e4270-198c-4b9a-83c9-63ad4de1ef6f.png">

**Comment by erdogant** [comment]
👍🏻🎉
