### ISSUE TITLE
Boostrapping bug - The data contains non-finite values

### ISSUE THREAD

**Issue by KrystofS** [erdogant/distfit#32]
The bootstrap call ends with `The data contains non-finite values.` exception. While when used by using n_jobs > 10 in distfit constructor this does not occur on the same dataset. I've included code for reproduction complete with test data in the linked zip file.

[repro.zip](https://github.com/erdogant/distfit/files/10962284/repro.zip)

(The dataset contains only positive finite floats.)

**Comment by erdogant** [comment]
Thank you for posting and with the example data set! I fixed the bug.
update to the latest version with: `pip install -U distfit`

**Comment by KrystofS** [comment]
Thank you for the quick fix.
