### ISSUE TITLE
Discrete data fit

### ISSUE THREAD

**Issue by koko12131** [erdogant/distfit#4]
Thanks a lot for this useful tool. But if my data is not continuous but discrete, ex Integers,  what should I do ?

**Comment by erdogant** [comment]
Checkout this question/answer on stackoverflow:
https://stackoverflow.com/a/62339711/13730780

Let me know wether this helps!

**Comment by koko12131** [comment]
thank you  for your very quick reply. The Q/A really helped me. But there is another question about the Q/A in which a parameter-"smooth=10" was used to work with integers. My question is how to determine the value of  parameter-"smooth"?

**Comment by erdogant** [comment]
This seems to depend on the number of samples that is being used.
I restructured the sphinx pages, and included a new section to examine integer fitting and the effect of the smooting parameter.

For both continuous and integer values, the conclusion is that the smooting window seems only to be usefull with very small samples sizes. Check out the sphinx pages for code and figures that support this conclusion.

https://erdogant.github.io/distfit/pages/html/Performance.html#integer-fitting

**Comment by koko12131** [comment]
thank you so much for your constructive comments！this does help me a lot！

**Comment by erdogant** [comment]
For future references; https://erdogant.github.io/distfit/pages/html/Discrete.html
