### ISSUE TITLE
Adjusting the bin size of plots

### ISSUE THREAD

**Issue by Siinan29** [erdogant/distfit#46]
Is it possible to adjust the bin size of the histograms?

**Comment by erdogant** [comment]
This was the only parameter that was not adjustable. I also changed that now.

```
from distfit import distfit
import numpy as np
X = np.random.normal(0, 2, 10000)

dfit = distfit()
dfit.fit_transform(X)
dfit.plot(bar_properties={'width':0.1})

```

update to the latest version with: `pip install -U distfit`
