### ISSUE TITLE
Fitting distribution for discrete/categorical data

### ISSUE THREAD

**Issue by ogreyesp** [erdogant/distfit#5]
Hi

Is it possible to fit a distribution with distfit library for a discrete variable? For example, let's say I have a survey that has 10 questions with possible values that go from 1 (poor) to 5 (excellent), and 100 persons take the survey. 

Best regards

**Comment by erdogant** [comment]
Have you seen the previous issue about integer values? It sounds similar to yours.

https://github.com/erdogant/distfit/issues/4

Let me know whether this helps.

**Comment by ogreyesp** [comment]
Hi, 

Thank you for your response. Yes, I have previously seen this answer... However, I suppose that when I will subsequently try to sample some random numbers from the best fitted distribution, the random numbers will be not exactly integers, but floats, isn´t it?

Following with your example, if we do

best_distr["distr"].rvs(*best_distr["params"], size=10)

the result is:

array([42.43419208, 43.9193906 , 39.83836361, 46.84268631,  6.40314481,
        6.14620859, 39.51184439,  8.06064685,  5.75366875, 27.2441456 ])

The only thing that I can do right now is to round these numbers and convert it to integers. However, certainly the distribution is not a discrete one, it is still a continuos one.

**Comment by erdogant** [comment]
Good point. Im going to look into this.

**Comment by wgmueller1** [comment]
The R package fitdistrplus has an option where a user can specify that the distribution is discrete.    I believe they support binomial, poisson, and negative binomial.   If you are planning on implementing discrete distributions it might nice to include a discrete option in the fit function or the instantiation of the distfit object.

**Comment by erdogant** [comment]
I worked on the implementation of discrete fitting using the binomial distribution. This is now possible in the latest version:

```
# Update to latest version
pip install -U distfit
import distfit
print(distfit.__version__)

This should be >= 1.2.7
```

Examples for discrete fitting can be found in the readme, sphinx pages and colab notebook:
https://colab.research.google.com/github/erdogant/distfit/blob/master/notebooks/distfit.ipynb
https://erdogant.github.io/distfit/pages/html/Discrete.html
