### ISSUE TITLE
Add loggamma

### ISSUE THREAD

**Issue by tirthajyoti** [erdogant/distfit#6]
I have a problem where [`loggamma`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.loggamma.html) fits best. I ran your script and my own custom script, they agree on `beta` parameters but the `loggamma` seemed much more natural. If it's not too much trouble, please consider adding this. If you are using `scipy.stats`, then it's the same API as others.

Cool project.

**Comment by erdogant** [comment]
Thanks! The loggamma is already part of distfit.
For example:

```
from distfit import distfit
X = np.random.normal(0, 2, 5000)
y = [-8,-6,0,1,2,3,4,5,6]
dist = distfit(distr='loggamma')
dist.fit_transform(X)
dist.plot()

```
Is this what you mean?

**Comment by tirthajyoti** [comment]
Yes, it is what I meant. However, is it not included in your regular default/popular run? 

When I ran,

```
dist = distfit(todf=True)
dist.fit_transform(dataset)
dist.plot()
```

The result did not include `loggamma` and the lowest RSS was for the `beta` which produced large, unnatural parameters.  In my case, the `loggamma` produced a far lower RSS score and would have been selected as the best one in the default run. I guess it's not that popular, so your `popular` choice does not include it.

You can close the issue now.

**Comment by erdogant** [comment]
Well, "popular" is not a fixed list. I included loggamma in the list.

Update with:

`pip install -U distfit`
