### ISSUE TITLE
Statistical distance measures?

### ISSUE THREAD

**Issue by tirthajyoti** [erdogant/distfit#7]
Cool project. Did you consider adding common distance scores like  [wasserstein_distance](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html#scipy.stats.wasserstein_distance) to determine the best fit as well?

**Comment by erdogant** [comment]
Good suggestion!
Four statistics are now available in the latest version: 'RSS', 'wasserstein', 'ks', 'energy'

```
pip install -U distfit
import distfit
print(distfit.__version__)

```
The version should be >= 1.2.8

Example: 

```
from distfit import distfit
X = np.random.normal(0, 2, 5000)
y = [-8,-6,0,1,2,3,4,5,6]
dist = distfit(stats='RSS')
dist = distfit(stats='wasserstein')
dist.fit_transform(X)
dist.plot_summary()
dist.plot()

```
