### ISSUE TITLE
`generate` or `rvs` method?

### ISSUE THREAD

**Issue by tirthajyoti** [erdogant/distfit#8]
Do you plan to have a `generate` or `rvs` method added to a fitted `dist` class to generate a given number (chosen by a `size` parameter) of new points with the best-fitted distribution? Here is the imagined code (say I have a dataset called `dataset`)

```
dist = distfit(todf=True)
dist.fit_transform(dataset)

# Newly generated 1000 points from the best-fitted distribution (based on some score criteria)
new_data = dist.generate(size=1000)
```

**Comment by erdogant** [comment]
Yes I like it! And implemented it!

```
pip install -U distfit
import distfit
print(distfit.__version__)

```
The version should be >= 1.4.0

Examples can be found in the readme and sphinx documentation pages.

**Comment by tirthajyoti** [comment]
This is working very nicely. You can close this issue.
