### ISSUE TITLE
New `anomaly` method?

### ISSUE THREAD

**Issue by tirthajyoti** [erdogant/distfit#9]
Is it possible to create a utility method '`anomaly` with the existing functions you already have? This is for anomaly detection in 1-D time series or sensor data streams, for which your package is ideally suited. Basically, you can use the `predict` method and put a small wrapper around it like this,

```
def anomaly(arr, prob_thresh=0.001):
    """
    Predicts (binary) whether data in a given array are anomalies or not 
    based on a prob threshold cutoff value. If the data point has a high probability 
    of coming from the fitted distribution, then return 'False' i.e. not an anomaly, else 'True'
    """
    preds = dist.predict(arr)
    return preds['y_proba'] < prob_thresh
```

**Comment by erdogant** [comment]
Thank you for this suggestion. Time flies having fun but I included `y_bool` (`y_proba<=alpha`) in the output of the `predict` function.
